# Generated by Django 3.2.9 on 2021-12-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_rename_contatos_contatodj'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatodj',
            name='exibir',
            field=models.BooleanField(default=True),
        ),
    ]
